# Railway Nixpacks configuration for Chrome and Selenium

[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.venv', 'chromium', 'chromedriver']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'python main.py'
